site_name: Open Curriculai
site_url: https://www.opencurricul.ai
site_author: Julien Beaulieu

repo_name: opencurriculai/data_science_curriculum
repo_url: https://github.com/opencurriculai/data_science_curriculum

theme:
  name: material
  favicon: assets/images/logo_teal_svg.svg
  logo: assets/images/logo_teal_svg.svg
  features:
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
  palette:
    scheme: default
    primary: teal
plugins:
  - mkdocstrings
extra_css: [assets/css/extra.css]
markdown_extensions:
  - admonition
  - meta
  - attr_list
  - pymdownx.details
  - pymdownx.critic
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
extra:
  analytics:
    provider: google
    property: G-88C824C820
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/opencurriculai/data_science_curriculum
    - icon: fontawesome/brands/discord
      link: https://discord.gg/cfgtzBwDXR
nav:
  - Home: 
    - Open Curriculai: "index.md"
    - Curriculum: "curriculum.md"
    - Resource Hub: "resource_hub/index.md"
    - Contributing: "contributing.md"
    - About: "about.md"
  - Curriculum: 
    - Data Science Curriculum: "curriculum.md"
    - Resource Hub: "resource_hub/index.md"
    - Contributing: "contributing.md"
    - About: "about.md"
  - Resource Hub:
    - Overview: "resource_hub/index.md"
    - Math: "resource_hub/math/index.md"
    - Machine Learning: "resource_hub/machine_learning/index.md"
    - Deep Learning: "resource_hub/deep_learning/index.md"
    - Data Engineering & MLOps: "resource_hub/data_engineering/index.md"
    - Tool Tutorials: "resource_hub/tool_tutorials/index.md"
    - Career: "resource_hub/career/index.md"
    - Social: "resource_hub/social/index.md"
    - Meta Learning: "resource_hub/meta_learning/index.md"
    - Other Curations: "resource_hub/other_curations/index.md"
  - Contributing: "contributing.md"
  - About: "about.md"



